from .binary_diags import get_binary_diagnostic
from .binary_diags import get_oxy_co2_diagnostic
from .instruction_parse import move_with_aim_and_depth
from .instruction_parse import move_with_instructions
from .measure_movement import measure_depth
from .measure_movement import measure_threes_depth
from .squid_bingo import play_squid_bingo